log4j:
  logger:
    org:
      hibernate:
        SQL: 'debug '
        type: 'trace '
logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.JpaAutoConfiguration
  cache:
    type: redis
  jackson:
    property-naming-strategy: SNAKE_CASE
  profiles:
    include:
      - datasource-wordbook
      - datasource-auth
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
